### ISSUE TITLE
`parity --config=dev` doesn't shutdown correctly

### ISSUE THREAD

**Issue by vrde** [openethereum/openethereum#10378]
- **Parity Ethereum version**: 2.3.2-beta-678138f-20190203
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: development network
- **Restarted**: yes

When I run `parity --config=dev` and try to kill it with `ctrl+c` it hangs forever, see the following log:

```
➜  ~ parity --config=dev
2019-02-19 01:06:08  Starting Parity-Ethereum/v2.3.2-beta-678138f-20190203/x86_64-linux-gnu/rustc1.31.1
2019-02-19 01:06:08  Keys path /home/vrde/.local/share/io.parity.ethereum/keys/DevelopmentChain
2019-02-19 01:06:08  DB path /home/vrde/.local/share/io.parity.ethereum/chains/DevelopmentChain/db/1484bce8c021f2ca
2019-02-19 01:06:08  State DB configuration: fast
2019-02-19 01:06:08  Operating mode: active
2019-02-19 01:06:08  Configured for DevelopmentChain using InstantSeal engine
2019-02-19 01:06:13  Public node URL: enode://60366b486fae829c6424e900bdeb0bfab17bca0dcbbb456a5f8715d36de823c741b85d62af448ef93e4f163d0682959df5c9380a95f8c9291520ed90171f54c0@192.168.0.3:30303
^C2019-02-19 01:06:36  Finishing work, please wait...
2019-02-19 01:07:36  Shutdown is taking longer than expected.
^C^\[1]    12958 quit (core dumped)  parity --config=dev
```

Edit: I've just noticed #10364. The issue looks the same. Mine might be easier to reproduce.

**Comment by joshua-mir** [comment]
Can you try shutting down with `--logging shutdown`?

**Comment by joshua-mir** [comment]
(I know that I was messing around with dev on beta 2.3.3 earlier today and didn't see this issue so there must be more to it than just running on dev)

**Comment by vrde** [comment]
```
➜  ~ parity --config=dev --logging shutdown
2019-02-19 01:16:22  main INFO parity_ethereum::run  Starting Parity-Ethereum/v2.3.2-beta-678138f-20190203/x86_64-linux-gnu/rustc1.31.1
2019-02-19 01:16:22  main INFO parity_ethereum::run  Keys path /home/vrde/.local/share/io.parity.ethereum/keys/DevelopmentChain
2019-02-19 01:16:22  main INFO parity_ethereum::run  DB path /home/vrde/.local/share/io.parity.ethereum/chains/DevelopmentChain/db/1484bce8c021f2ca
2019-02-19 01:16:22  main INFO parity_ethereum::run  State DB configuration: fast
2019-02-19 01:16:22  main INFO parity_ethereum::run  Operating mode: active
2019-02-19 01:16:22  main INFO ethcore_service::service  Configured for DevelopmentChain using InstantSeal engine
2019-02-19 01:16:27  IO Worker #2 INFO network  Public node URL: enode://60366b486fae829c6424e900bdeb0bfab17bca0dcbbb456a5f8715d36de823c741b85d62af448ef93e4f163d0682959df5c9380a95f8c9291520ed90171f54c0@192.168.0.3:30303
^C2019-02-19 01:16:34  main INFO parity_ethereum::run  Finishing work, please wait...
2019-02-19 01:16:34  main TRACE shutdown  [IoService] Closing...
2019-02-19 01:16:34   TRACE shutdown  [IoWorker] Closing...
2019-02-19 01:16:34   TRACE shutdown  [IoWorker] Closed
2019-02-19 01:16:34   TRACE shutdown  [IoWorker] Closing...
2019-02-19 01:16:34   TRACE shutdown  [IoWorker] Closed
2019-02-19 01:16:34   TRACE shutdown  [IoWorker] Closing...
2019-02-19 01:16:34   TRACE shutdown  [IoWorker] Closed
2019-02-19 01:16:34   TRACE shutdown  [IoWorker] Closing...
2019-02-19 01:16:34   TRACE shutdown  [IoWorker] Closed
2019-02-19 01:16:34  main TRACE shutdown  [IoService] Closed.
2019-02-19 01:17:34  main WARN parity_ethereum::run  Shutdown is taking longer than expected.
2019-02-19 01:21:34  main WARN parity_ethereum::run  Shutdown timeout reached, exiting uncleanly.
```

**Comment by joshua-mir** [comment]
I should probably stop asking for that specific logging module because I've never seen useful output from it 🙏 thanks, I'll look into this more tomorrow morning.

**Comment by gpersoon** [comment]
**Parity Ethereum version:** version Parity-Ethereum/v2.5.0-beta-b52ac2066-20190408/x86_64-windows-msvc/rustc1.33.0
**Operating system:** Windows
**Installation:** downloaded.exe
**Fully synchronized:** no
**Network:** development network
**Restarted:** no

Start parity.exe --config dev   // note account hasn't been unlocked
Do a transaction with eth_sendTransaction: 
curl -H "Content-Type: application/json" -g --data " {""jsonrpc"":""2.0"",""method"":""eth_sendTransaction"",""params"":[{  
""from"": ""0x00a329c0648769a73afac7f9381e08fb43dbea72"",  
""to"": ""0x00a329c0648769a73afac7f9381e08fb43dbea72"",  
""value"": ""0x1""  } ],""id"":1}"  http://localhost:8545    
// note windows requires "" 
The curl command doesn't finish
Ctrl-c on parity.exe : doesn't finish
However with the account unlocked parity stops without any problem
Note: no warning is given that the account isn't unlocked

**Comment by joshua-mir** [comment]
It sounds like the Signer is blocking the shutdown process, thanks for the report @gpersoon - could you please try running with `-l signer` and share your logs if possible?

**Comment by gpersoon** [comment]
I've add the logfiles. If you need any other logfiles please let me know.
[log-without-unlock.txt](https://github.com/paritytech/parity-ethereum/files/3148670/log-without-unlock.txt)
[log-with-unlock.txt](https://github.com/paritytech/parity-ethereum/files/3148671/log-with-unlock.txt)

**Comment by dvdplm** [comment]
Probably fixed by https://github.com/paritytech/parity-ethereum/pull/10689

**Comment by gpersoon** [comment]
I just compiled the current github version and it still has the shutdown issue.
This is the output:
2019-06-07 21:28:18  Starting Parity-Ethereum/v2.6.0-nightly-7827cc048-20190607/x86_64-windows-msvc/rustc1.35.0
....
2019-06-07 21:28:23  Public node URL: enode://....@127.0.0.1:30303
2019-06-07 21:28:36  eth_sendTransaction is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.
2019-06-07 21:28:44  Finishing work, please wait...
2019-06-07 21:29:44  Shutdown is taking longer than expected.
2019-06-07 21:33:44  Shutdown timeout reached, exiting uncleanly.
'''

**Comment by dvdplm** [comment]
@gpersoon I tried this in a virtualbox using a recent build and shutdown seems to work here. I'll figure out a way to give you the same build I used to try on your end.

```
C:\Users\IEUser\Downloads>parity.exe --config=dev
2019-06-08 11:49:35  Starting Parity-Ethereum/v2.6.0-nightly-7827cc048-20190607/x86_64-windows-msvc/rustc1.34.2
2019-06-08 11:49:35  Keys path C:\Users\IEUser\AppData\Roaming\Parity\Ethereum\keys\DevelopmentChain
2019-06-08 11:49:35  DB path C:\Users\IEUser\AppData\Local\Parity\Ethereum\chains\DevelopmentChain\db\1484bce8c021f2ca
2019-06-08 11:49:35  State DB configuration: fast
2019-06-08 11:49:35  Operating mode: active
2019-06-08 11:49:35  Configured for DevelopmentChain using InstantSeal engine
2019-06-08 11:49:35  Cannot read logs: Io(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })
2019-06-08 11:49:35  Listening for new connections on 127.0.0.1:8546.
2019-06-08 11:49:35  Multi-threaded server is not available on Windows. Falling back to single thread.
2019-06-08 11:49:40  Public node URL: enode://c6d5cd4622a4d1fd6d3388b77cca6f8f45b672391cb20b5dd5108c7d1892fb9c832ee2e0a0d52db9401c046565309cb42f4a2f508283764654b9744897d5e780@127.0.0.1:30303
2019-06-08 11:50:02  Finishing work, please wait...
```

**Comment by dvdplm** [comment]
@gpersoon If you go [here](https://gitlab.parity.io/parity/parity-ethereum/-/jobs/159620) and click the "Download" button you can try the same branch I tried. Can you let us know if the shutdown issue still persists with that build? Thanks.

**Comment by gpersoon** [comment]
The shutdown still doesn't work for me (after have down the curl as shown above; without the curl it stops) - i guess it is somehow waiting the account unlock

```javascript
C:\blockchain_test\Parity>.\parity.exe --config dev
2019-06-12 15:41:12  Starting Parity-Ethereum/v2.6.0-nightly-7827cc048-20190607/x86_64-windows-msvc/rustc1.34.2
2019-06-12 15:41:12  Keys path C:\Users\gerar\AppData\Roaming\Parity\Ethereum\keys\DevelopmentChain
2019-06-12 15:41:12  DB path C:\Users\gerar\AppData\Local\Parity\Ethereum\chains\DevelopmentChain\db\1484bce8c021f2ca
2019-06-12 15:41:12  State DB configuration: fast
2019-06-12 15:41:12  Operating mode: active
2019-06-12 15:41:12  Configured for DevelopmentChain using InstantSeal engine
2019-06-12 15:41:12  Cannot read logs: Io(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })
2019-06-12 15:41:12  Listening for new connections on 127.0.0.1:8546.
2019-06-12 15:41:12  Multi-threaded server is not available on Windows. Falling back to single thread.
2019-06-12 15:41:17  Public node URL: enode://5a9195f21f7a306a346ed56b2210a5bc51672dfd16e89308b9d6570d9c9ebb53c70b5b42b79bed2afbd44b6f39f83e862e8f683825229deab508f8e277b5ac33@127.0.0.1:30303
2019-06-12 15:41:31  eth_sendTransaction is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.
2019-06-12 15:41:47     0/25 peers      8 KiB chain   12 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2019-06-12 15:42:17     0/25 peers      8 KiB chain   12 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2019-06-12 15:42:26  Finishing work, please wait...
2019-06-12 15:43:26  Shutdown is taking longer than expected.
2019-06-12 15:47:26  Shutdown timeout reached, exiting uncleanly.
'''

**Comment by gpersoon** [comment]
I've tried the latest build and i still see the issue:

```rust
>.\parity.exe --config dev
2019-07-22 10:51:28  Starting Parity-Ethereum/v2.7.0-nightly-d1b28bf57-20190721/x86_64-windows-msvc/rustc1.36.0
2019-07-22 10:51:28  Keys path C:\Users\gerar\AppData\Roaming\Parity\Ethereum\keys\DevelopmentChain
2019-07-22 10:51:28  DB path C:\Users\gerar\AppData\Local\Parity\Ethereum\chains\DevelopmentChain\db\1484bce8c021f2ca
2019-07-22 10:51:28  State DB configuration: fast
2019-07-22 10:51:28  Operating mode: active
2019-07-22 10:51:29  Configured for DevelopmentChain using InstantSeal engine
2019-07-22 10:51:29  Multi-threaded server is not available on Windows. Falling back to single thread.
2019-07-22 10:51:34  Public node URL: enode://5a9195f21f7a306a346ed56b2210a5bc51672dfd16e89308b9d6570d9c9ebb53c70b5b42b79bed2afbd44b6f39f83e862e8f683825229deab508f8e277b5ac33@127.0.0.1:30303
2019-07-22 10:51:59     0/25 peers   735 bytes chain   17 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-22 10:52:17  eth_sendTransaction is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.
2019-07-22 10:52:29     0/25 peers   735 bytes chain   17 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-22 10:52:44  Finishing work, please wait...
2019-07-22 10:53:45  Shutdown is taking longer than expected.
2019-07-22 10:57:45  Shutdown timeout reached, exiting uncleanly.
```
