### ISSUE TITLE
Android test builds do not compile

### ISSUE THREAD

**Issue by 5chdn** [openethereum/openethereum#9721]
- **Parity Ethereum version**: 2.1.2
- **Operating system**: Android
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

Android builds do not compile

```
    Checking tokio-retry v0.1.1
    Checking tokio-named-pipes v0.1.0 (https://github.com/nikvolf/tokio-named-pipes#0b9b728e)
    Checking tokio-uds v0.1.7
error[E0425]: cannot find function `get_peer_cred` in module `ucred`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-uds-0.1.7/src/lib.rs:310:16
    |
310 |         ucred::get_peer_cred(self)
    |                ^^^^^^^^^^^^^ not found in `ucred`

   Compiling ring v0.12.1 (https://github.com/paritytech/ring#bae475e9)
    Checking env_logger v0.5.13
error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `tokio-uds`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Command exited with non-zero status 101
301.83user 30.22system 3:04.98elapsed 179%CPU (0avgtext+0avgdata 383416maxresident)k
0inputs+1444384outputs (8443major+5272898minor)pagefaults 0swaps
ERROR: Job failed: exit code 1
```

**Comment by 5chdn** [comment]
https://gitlab.parity.io/parity/parity-ethereum/-/jobs/103462

**Comment by niklasad1** [comment]
Fixed by https://github.com/paritytech/parity-ethereum/pull/9657

**Comment by gabreal** [comment]
> error[E0463]: can't find crate for `proc_macro`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.20/src/lib.rs:53:1
   |
53 | extern crate proc_macro;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error


I'm still seeing this error on android builds (https://gitlab.parity.io/gabriel/parity-ethereum/-/jobs/106947). Is this related or shall I open an other issue?

**Comment by niklasad1** [comment]
@gabreal 

Android actually builds fine but the test build fails and this seems related to `proc_macro`. If you change the title of the issue then it's fine to keep it. But, still I think it's a bit overkill to run the tests on `android` for now

citing @tomaka 
> According to https://github.com/dtolnay/proc-macro-hack/issues/6 you shouldn't put extern crate proc_macro; in any dependency. The build will fail on some platforms only, and that seems to include Android for example

**Comment by adria0** [comment]
Closing issue due to its stale state.
